Repository inhibitor1217/coffee-hmm, pull requests merged in 2021-03, with the labels that each got.

#72 Update README.md
  README.md
Labels: documentation

#71 hotfix: build error
  services/http-api/README.md
  services/http-api/package.json
  services/http-api/src/entities/place.ts
  services/http-api/src/routes/cafe/index.test.ts
  services/http-api/src/routes/place/index.test.ts
  services/http-api/src/routes/place/place.control.ts
  services/http-api/src/test/util.ts
Labels: backend

#78 feat: 메인화면 장소 추가를 위한 코드 수정
  app/src/components/others/PlaceSlide/index.css
  app/src/components/pages/Intro/index.css
  app/src/components/pages/Intro/index.tsx
Labels: frontend

#81 feat: google-material-icon에서 이미지 아이콘으로 대체
  app/public/icons/baseline_navigate_before_black_18dp.png
  app/public/icons/like-icon.png
  app/public/icons/share-icon.png
  app/public/index.html
  app/src/components/common/Footer/index.css
  app/src/components/common/Header/index.css
  app/src/components/common/Header/index.tsx
  app/src/components/common/Logo/index.css
  app/src/components/others/CafeDetail/index.css
  app/src/components/others/CafeDetail/index.tsx
  app/src/components/others/CafeDetailImageCarousel/index.css
  app/src/components/others/NoSearchResult/index.css
  app/src/components/others/SearchBar/index.css
  app/src/components/others/WebSearchBottomPopup/index.css
  app/src/index.css
Labels: frontend

#82 hotfix: correct location of seo files
  app/public/robots.txt
  app/public/sitemap.xml
  app/robots.txt
Labels: bug, frontend

#80 feat: 메인 페이지 이미지 로딩 전 대기 페이지 추가
  app/public/images/coffee.jpg
  app/public/images/macaron-icon.jpg
  app/public/index.html
  app/src/components/others/CafeByPlace/index.tsx
  app/src/components/others/CafeCarousel/index.tsx
  app/src/components/others/CarouselMainImage/index.tsx
  app/src/components/others/InitialLoading/index.css
  app/src/components/others/InitialLoading/index.tsx
  app/src/components/pages/Intro/index.tsx
Labels: frontend

#83 fix: correct typo of sitemap.xml
  app/public/sitemap.xml
Labels: bug

#87 feat: 이미지 로드 전 화면 공백 현상 해결
  app/src/components/Router.tsx
  app/src/components/others/CafeByPlace/index.tsx
  app/src/components/others/CafeCarousel/index.tsx
  app/src/components/others/CarouselMainImage/index.tsx
  app/src/components/pages/Intro/index.tsx
  app/src/store/modules/intro-nav.ts
Labels: bug, frontend

#96 Separate firebase project for development/production stage
  app/package.json
  app/public/index.html
  app/src/components/App.tsx
  app/src/components/Router.tsx
  app/src/hooks/useAnalyticsPageView.ts
  app/src/hooks/useFirebase.ts
  app/src/utils/function.tsx
Labels: frontend, refactor

#97 Use @inhibitor1217/react-swipeablepanel
  app/package.json
  app/src/components/others/CafeByPlace/index.css
  app/src/components/others/CafeByPlace/index.tsx
  app/src/components/others/CafeByPlace/styled.tsx
  app/src/components/others/CafeDetailImageCarousel/index.css
  app/src/components/others/CafeDetailImageCarousel/index.tsx
  app/src/components/others/CafeMainImageCarousel/index.tsx
  app/src/components/others/CarouselHorizontal/index.css
  app/src/components/others/CarouselHorizontal/index.tsx
  app/src/components/pages/Intro/index.css
  app/src/components/pages/Intro/index.tsx
Labels: frontend, refactor

#90 Feature/app/v2.1.5
  app/package.json
  app/public/index.html
  app/src/components/App.tsx
  app/src/components/Router.tsx
  app/src/components/common/Footer/index.css
  app/src/components/common/Footer/index.tsx
  app/src/components/others/CafeByPlace/index.css
  app/src/components/others/CafeByPlace/index.tsx
  app/src/components/others/CafeByPlace/styled.tsx
  app/src/components/others/CafeCarousel/index.css
  app/src/components/others/CafeCarousel/index.tsx
  app/src/components/others/CafeDetailImageCarousel/index.css
  app/src/components/others/CafeDetailImageCarousel/index.tsx
  app/src/components/others/CafeList/index.css
  app/src/components/others/CafeList/index.tsx
  app/src/components/others/CafeMainImageCarousel/index.tsx
  app/src/components/others/CarouselHorizontal/index.css
  app/src/components/others/CarouselHorizontal/index.tsx
  app/src/components/others/CarouselVertical/index.css
  app/src/components/others/CarouselVertical/index.tsx
  app/src/components/others/NoSearchResult/index.css
  app/src/components/others/NoSearchResult/index.tsx
  app/src/components/others/SearchBar/index.css
  app/src/components/others/SearchBar/index.tsx
  app/src/components/others/WebSearchBottomPopup/index.css
  app/src/components/others/WebSearchBottomPopup/index.tsx
  app/src/components/pages/Intro/index.css
  app/src/components/pages/Intro/index.tsx
  app/src/hooks/useAnalyticsPageView.ts
  app/src/hooks/useFirebase.ts
  app/src/utils/function.tsx
  app/src/utils/styled.tsx
Labels: release

#99 fix: 이미지 사이즈 수정 및 이미지 하단 index-dot 표시 오류 대응
  app/src/components/common/Header/index.css
  app/src/components/common/Header/index.tsx
  app/src/components/others/CafeByPlace/index.css
  app/src/components/others/CafeByPlace/styled.tsx
  app/src/components/others/CafeDetail/index.css
  app/src/components/others/CafeDetail/index.tsx
  app/src/components/others/CafeDetailImageCarousel/index.css
  app/src/components/others/CarouselDetailImage/index.css
  app/src/components/others/CarouselMainImage/index.css
  app/src/components/others/PositionDotHorizontal/index.tsx
  app/src/components/pages/Detail/index.css
  app/src/index.css
Labels: bug, frontend

#100 Add placeId, placeName parameters to GET /cafe/count and GET /cafe/list
  services/http-api/README.md
  services/http-api/src/routes/cafe/cafe.control.ts
  services/http-api/src/routes/cafe/list.test.ts
Labels: backend
