Repository inhibitor1217/coffee-hmm, pull requests merged in 2021-06, with the labels that each got.

#134 chore(deps): bump browserslist from 4.16.3 to 4.16.6 in /jobs
  jobs/yarn.lock
Labels: dependencies

#135 chore(deps): bump ws from 7.4.4 to 7.4.6 in /jobs
  jobs/yarn.lock
Labels: dependencies

#136 chore(deps): bump ws from 7.4.5 to 7.4.6 in /services/auth
  services/auth/yarn.lock
Labels: dependencies

#137 chore(deps): bump ws from 7.4.5 to 7.4.6 in /services/http-api
  services/http-api/yarn.lock
Labels: dependencies

#133 fix: 장소 버튼 정렬 수정
  app/package.json
  app/src/components/App.tsx
  app/src/components/Router.tsx
  app/src/components/api/index.tsx
  app/src/components/common/Header/index.css
  app/src/components/common/Header/index.tsx
  app/src/components/common/Logo/index.css
  app/src/components/common/Logo/index.tsx
  app/src/components/others/CafeByPlace/index.tsx
  app/src/components/others/CafeDetail/index.css
  app/src/components/others/CafeDetail/index.tsx
  app/src/components/others/CafeDetailImageCarousel/index.tsx
  app/src/components/others/CafeMainImageCarousel/index.tsx
  app/src/components/others/CarouselDetailImage/index.tsx
  app/src/components/others/CarouselMainImage/index.tsx
  app/src/components/others/PlaceSlide/index.css
  app/src/components/others/PlaceSlide/index.tsx
  app/src/components/pages/Detail/index.tsx
  app/src/components/pages/Intro/index.tsx
  app/src/constants/direction.ts
  app/src/constants/enums/appStage.ts
  app/src/constants/image.ts
  app/src/constants/index.ts
  app/src/constants/initialState.ts
  app/src/constants/url.ts
  app/src/hooks/useAnalyticsPageView.ts
  app/src/hooks/useFirebase.ts
  app/src/index.css
  app/src/store/modules/cafe.ts
  app/src/store/selectors/cafe.ts
  app/src/types/cafe.ts
  app/src/types/index.ts
  app/src/types/place.ts
  app/src/utils/appStage.ts
  app/src/utils/constant.tsx
  app/src/utils/copyLink.ts
  app/src/utils/function.tsx
  app/src/utils/getOrder.ts
  app/src/utils/index.ts
  app/src/utils/onImageLoad.ts
  app/src/utils/openSearch.ts
  app/src/utils/reducerCarousel.ts
  app/src/utils/styled.tsx
  app/tsconfig.json
  app/tsconfig.paths.json
Labels: frontend

#138 Prettier 관련 에러 수정
  app/.prettierrc.json
  app/.vscode/settings.json
  app/package.json
  app/src/components/DesktopFallback.tsx
  app/src/components/PageTemplate.tsx
  app/src/components/Router.tsx
  app/src/components/api/index.tsx
  app/src/components/common/Header/index.tsx
  app/src/components/common/Spinner/index.tsx
  app/src/components/others/CafeByPlace/styled.tsx
  app/src/components/others/CafeMainImageCarousel/index.tsx
  app/src/components/others/InitialLoading/index.tsx
  app/src/components/others/PlaceSlide/index.tsx
  app/src/components/others/PositionDotHorizontal/index.tsx
  app/src/components/pages/Intro/index.tsx
  app/src/hooks/useFirebase.ts
  app/src/index.tsx
  app/src/store/hooks.ts
  app/src/store/index.ts
  app/src/store/modules/cafe.ts
  app/src/store/modules/intro-nav.ts
  app/src/utils/openSearch.ts
  app/src/utils/styled.tsx
Labels: hotfix

#139 CI release-app 스크립트에서 CI = true 옵션으로 인해 warning으로 터지는 점 수정
  .github/workflows/release-app.yml
Labels: hotfix
