Repository inhibitor1217/coffee-hmm, pull requests merged in 2021-05, with the labels that each got.

#111 GET /place/list 각 place에 cafeCount 필드 추가
  services/http-api/README.md
  services/http-api/src/routes/place/index.test.ts
  services/http-api/src/routes/place/place.control.ts
Labels: backend, feature

#110 Feature/app/v2.2.0
  app/public/icons/plane.png
  app/public/index.html
  app/src/components/common/Header/index.css
  app/src/components/common/Header/index.tsx
  app/src/components/others/CafeByPlace/index.css
  app/src/components/others/CafeByPlace/index.tsx
  app/src/components/others/CarouselMainImage/index.tsx
  app/src/utils/constant.tsx
Labels: feature, frontend

#114 이미지 패널 자동 swipe 적용
  app/src/components/others/CafeDetailImageCarousel/index.tsx
  app/src/components/others/CafeMainImageCarousel/index.tsx
Labels: feature, frontend

#116 이미지가 2장일 때 swipeable panel에서 발생하는 문제점 해결
  app/package.json
Labels: bug, frontend

#115 release: v2.2.1
  app/package.json
  app/src/components/others/CafeDetailImageCarousel/index.tsx
  app/src/components/others/CafeMainImageCarousel/index.tsx
Labels: frontend, release

#125 fix: correct ci script syntax error
  .github/workflows/ci-services.yml
Labels: bug

#126 back-merge: master to dev/server
  .github/workflows/ci-services.yml
Labels: merge-commit

#117 [APP] Eslint, Prettier 추가
  app/.eslintrc.json
  app/.prettierrc.json
  app/package.json
  app/src/components/App.tsx
  app/src/components/DesktopFallback.tsx
  app/src/components/PageTemplate.tsx
  app/src/components/Router.tsx
  app/src/components/api/index.tsx
  app/src/components/common/Header/index.tsx
  app/src/components/common/Spinner/index.tsx
  app/src/components/others/CafeByPlace/index.tsx
  app/src/components/others/CafeByPlace/styled.tsx
  app/src/components/others/CafeDetail/index.tsx
  app/src/components/others/CafeDetailImageCarousel/index.tsx
  app/src/components/others/CafeMainImageCarousel/index.tsx
  app/src/components/others/CarouselDetailImage/index.tsx
  app/src/components/others/CarouselMainImage/index.tsx
  app/src/components/others/InitialLoading/index.tsx
  app/src/components/others/PlaceSlide/index.tsx
  app/src/components/others/PositionDotHorizontal/index.tsx
  app/src/components/pages/Detail/index.tsx
  app/src/components/pages/Intro/index.tsx
  app/src/hooks/useAnalyticsPageView.ts
  app/src/hooks/useFirebase.ts
  app/src/index.tsx
  app/src/reportWebVitals.ts
  app/src/setupTests.ts
  app/src/store/hooks.ts
  app/src/store/modules/cafe.ts
  app/src/store/modules/intro-nav.ts
  app/src/store/selectors/cafe.ts
  app/src/utils/constant.tsx
  app/src/utils/function.tsx
  app/src/utils/styled.tsx
  app/src/utils/type.tsx
  app/tsconfig.json
Labels: frontend

#127 Update server url to production endpoint
  app/src/utils/constant.tsx
Labels: frontend
