Repository inhibitor1217/coffee-hmm, pull requests merged in 2021-10, with the labels that each got.

#201 Configure apple app association settings on web app
  app/public/.well-known/apple-app-site-association
  app/public/images/launcher.png
  app/public/index.html
Labels: frontend, feature

#202 chore: update version to 2.2.4, and adjust dependencies
  app/package.json
  app/yarn.lock
Labels: frontend, dependencies

#200 Create README.md
  README.md
Labels: documentation
